#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename;

my $filename = $ARGV[0];
my $dirname = dirname($filename);

system(sprintf("watcher --dir %s -- prove -lvc %s", $dirname, $filename));
